config/routes.rb
Rails.application.routes.draw do

  authenticate :user do
    get '/project_research_fields/project/:project_id', to: 'project_research_fields#index', as: 'project_research_fields_index'
    post '/project_research_fields/add/:research_field/project/:project_id', to: 'project_research_fields#add', as: 'project_research_fields_add'
    get 'contributions/project/:project_id' => 'contributions#contribute', as: 'submit_completion'
    get 'dashboard' => 'dashboard#index'
    get 'contributions/:project_id' => 'contributions#complete', as: 'project_contributions'
    get 'contributions/add/project/:project_id/user/:user_id' => 'contributions#add', as: 'add_contribution_to_project'
    post 'contributions/add/project/:project_id/user/:user_id' => 'contributions#save', as: 'save_contribution_to_project'
    post '/profile_research_fields/add/:research_field', to: 'profile_research_fields#add', as: 'profile_research_fields_add'
    get 'project/team/:project_id' => 'teams#new', as: 'add_user_to_project'
    post 'team/project/:project_id/user/:user_id' => 'teams#create', as: 'add_user_team'
    delete 'team/project/remove/:project_id/user/:user_id' => 'teams#destroy', as: 'remove_user_team'

    get 'search/projects/' => 'projects#search'
    post 'search/projects/' => 'projects#search', as: 'search_interesting_projects'
    resources :teams
    resources :contributions
    resources :projects do
      resources :iterations
    end
    resources :profile_research_fields
    resources :profiles
    resources :project_research_fields
    resources :tasks
    get 'iteration/:iteration_id/tasks/new' => 'tasks#new', as: 'new_iteration_tasks'
    post 'iteration/:iteration_id/tasks/new' => 'tasks#create'
    get 'iteration/:iteration_id/task/:id/edit' => 'tasks#edit', as: 'edit_iteration_task'
    post 'iteration/:iteration_id/task/:id/edit' => 'tasks#edit'

    resources :requests
    post 'requests/project/:project_id/:request_type' => 'requests#make', as: 'make_request'
    post 'requests/:id/:type' => 'requests#action', as: 'take_request_action'
    get 'requests/:id/remove/points' => 'requests#leave', as: 'leave_request_remove_points'
    patch 'requests/:id/remove/points' => 'requests#approve_leave'

  end

  devise_for :users, controllers: { registrations: "registrations" }

  root 'static_pages#home'










end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id               :integer          not null, primary key
#  name             :string
#  status           :integer
#  description      :string
#  start_date       :date
#  end_date         :date
#  funding          :decimal(10, 2)
#  difficulty_level :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  department_id    :integer
#  user_id          :integer
#










class Project < ActiveRecord::Base
  include Filterable

  scope :status, -> (status) { where status: status }

  enum status: [:not_started, :in_progress, :on_hold, :complete]
  enum difficulty_level: [:easy, :medium, :hard]
  
  validates :name,
            length: { maximum: 225 },
            presence: true
  validates :status,
            presence: true,
            inclusion: {
              in: statuses.keys,
              message: "must be either " + statuses.keys.join(" or ")
            }
  validates :description,
            presence: true,
            length: { maximum: 3000 }
  validates :start_date,
            date: { after_or_equal_to: Proc.new { Time.now-1.day }},
            presence: true
  validates :end_date,
            date: { after: :start_date},
            presence: true
  validates :funding,
            numericality: { greater_than_or_equal_to: 0},
            presence: true
  validates :difficulty_level,
            presence: true,
            inclusion: {
              in: difficulty_levels.keys,
              message: "must be either " + difficulty_levels.keys.join(" or ")
            }


  belongs_to :department
  belongs_to :user
  has_many :project_research_fields
  has_one :contribution
  has_many :teams
  has_many :requests
  has_many :iterations
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include Filterable

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects_created = Project.where('user_id == ?', current_user.id)
    @projects_created = @projects_created.status(Project.statuses[params[:status]]) if params[:status].present?

    @projects_collaborated = Team.where('user_id == ?', current_user.id).pluck(:project_id)
    @projects_collaborated = Project.where(:id => @projects_collaborated)

    @projects_collaborated = @projects_collaborated.status(Project.statuses[params[:status]]) if params[:status].present?

    @projects = (@projects_created + @projects_collaborated).sort_by(&:created_at).reverse!

    @total_projects_count = @projects.length

    @projects = @projects.paginate(:page => params[:page], :per_page => 5)
    @departments = Department.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    # @iterations = Iteration.all
    @iterations = Iteration.where('project_id = ?', @project.id)
    @team_members_ids = Team.where('project_id = ?', @project.id).pluck('user_id')

    @approved_join_requests = Request.where('user_id = ? and project_id = ? and type = ? and status = ?', current_user.id, @project.id, Request.request_types[:join], Request.request_statuses[:approved])
    @unapproved_join_requests = Request.where('user_id = ? and project_id = ? and type = ? and status = ?', current_user.id, @project.id, Request.request_types[:join], Request.request_statuses[:unapproved])
    @unapproved_leave_request = Request.where('user_id = ? and project_id = ? and type = ? and status = ?', current_user.id, @project.id, Request.request_types[:leave], Request.request_statuses[:unapproved])
    @approved_leave_request = Request.where('user_id = ? and project_id = ? and type = ? and status = ?', current_user.id, @project.id, Request.request_types[:leave], Request.request_statuses[:approved])

  end

  # GET /projects/new
  def new
    @project = Project.new
    @departments = Department.all
  end

  # GET /projects/1/edit
  def edit
    authorize
    @team = Team.new
    @departments = Department.all
    @users = User.all
  end

  # POST /projects
  # POST /projects.json
  def create

    @project = Project.new(project_params)
    @project.user_id =  current_user.id
    @departments = Department.all

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    authorize

    @project.user_id =  current_user.id
    @departments = Department.all

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    authorize

    project_id = params[:id]
    @iteration_ids = Iteration.where("project_id == ?", project_id).pluck(:id)
    @iterations_tasks = Task.where('iteration_id IN (?)', @iteration_ids)

    @project.destroy
    Team.where("project_id == ?", project_id).destroy_all
    Iteration.where("project_id == ?", project_id).destroy_all

    if @iteration_ids.length > 0 && @iterations_tasks.length > 0
      Task.where('iteration_id IN (?)', @iteration_ids).destroy_all
    end

    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @departments = Department.all
    if params[:search] && params[:department][:id]
      @projects_not_created = Project.where('department_id = ? and user_id != ?', params[:department][:id], current_user.id).distinct
      @projects_not_created = @projects_not_created.where('name like ? or description like ?', "%#{params[:search]}%", "%#{params[:search]}%") if params[:search] != ''

      @projects_not_collaborated_ids = Team.where('user_id != ?', current_user.id).distinct.pluck(:project_id)

      @projects_not_collaborated = Project.where(:id => @projects_not_collaborated_ids).where('department_id = ? and user_id != ?', params[:department][:id], current_user.id).distinct
      @projects_not_collaborated = @projects_not_collaborated.where('name like ? or description like ?', "%#{params[:search]}%", "%#{params[:search]}%") if params[:search] != ''

      @projects = (@projects_not_created + @projects_not_collaborated).sort_by(&:created_at).uniq.reverse!
      @total_projects_count = @projects.length
    else
      @projects = nil
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :status, :description, :start_date, :end_date, :funding, :difficulty_level, :user_id, :department_id)
  end

  def authorize
    if current_user != @project.user
      render :file => File.join(Rails.root, 'public/403'), :formats => [:html], :status => 403, :layout => false
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="authform">
  <%= form_for(@project) do |f| %>
      <%= display_error_messages(@project) %>
      <fieldset>
        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :department %><br>
          <% departments = options_from_collection_for_select(@departments, 'id', 'name') %>
          <%= f.select :department_id, departments, {:prompt => true}, {:class => 'form-control custom'} %>
        </div>

        <div class="form-group">
          <%= f.label :status %><br>
          <%= f.select :status, Project.statuses.keys.map { |status| [status.titleize, status] }, {}, class: 'form-control custom' %>
        </div>
        <div class="form-group">
          <%= f.label :description %><br>
          <%= f.text_field :description, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :start_date %><br>
          <%= f.date_select :start_date, {}, {:class => "form-control custom"} %>
        </div>
        <div class="form-group">
          <%= f.label :end_date %><br>
          <%= f.date_select :end_date, {}, {:class => "form-control custom"} %>
        </div>
        <div class="form-group">
          <%= f.label :funding %><br>
          <div class="input-group col-lg-5">
            <span class="input-group-addon">$</span>
            <%= f.number_field :funding, class: 'form-control' %>
            <span class="input-group-addon">.00</span>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :difficulty_level %><br>
          <%= f.select :difficulty_level,
                       Project.difficulty_levels.keys.map { |level| [level.titleize, level] }, {}, {:class => "form-control custom"} %>
        </div>
        <% if (@project.name != nil) %>
            <h1>Team Members
              <%= link_to raw('<i class="fa fa-plus-circle"></i> &nbsp;&nbsp;Add'), add_user_to_project_path(@project), :method => :get, class: 'btn btn-success btn-sm' %>
            </h1>

            <table class="table table-striped col-lg-6">
              <tbody>
              <% @project.teams.each do |team_member| %>
                  <tr>
                    <% if team_member.user.profile.first_name %>
                        <td><%= team_member.user.profile.first_name + ' ' + team_member.user.profile.last_name %>
                        <td>
                          <%= link_to raw('<i class="fa fa-trash"></i> &nbsp;&nbsp;Remove'), remove_user_team_path(@project, :user_id => team_member.user.id), data: {confirm: 'Are you sure?'}, :method => :delete, class: 'btn btn-danger btn-sm' %>
                        </td>
                    <% end %>
                  </tr>
              <% end %>
        <% end %>

        </tbody>
        </table>

        <%= f.submit 'Submit', :class => 'btn btn-lg btn-primary' %>
      </fieldset>

  <% end %>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<div class="authform">
  <%= form_for(@project) do |f| %>
      <%= display_error_messages(@project) %>
      <fieldset>
        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :department %><br>
          <% departments = options_from_collection_for_select(@departments, 'id', 'name') %>
          <%= f.select :department_id, departments, {:prompt => true}, {:class => 'form-control custom'} %>
        </div>

        <div class="form-group">
          <%= f.label :status %><br>
          <%= f.select :status, Project.statuses.keys.map { |status| [status.titleize, status] }, {}, class: 'form-control custom' %>
        </div>
        <div class="form-group">
          <%= f.label :description %><br>
          <%= f.text_field :description, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :start_date %><br>
          <%= f.date_select :start_date, {}, {:class => "form-control custom"} %>
        </div>
        <div class="form-group">
          <%= f.label :end_date %><br>
          <%= f.date_select :end_date, {}, {:class => "form-control custom"} %>
        </div>
        <div class="form-group">
          <%= f.label :funding %><br>
          <div class="input-group col-lg-5">
            <span class="input-group-addon">$</span>
            <%= f.number_field :funding, class: 'form-control' %>
            <span class="input-group-addon">.00</span>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :difficulty_level %><br>
          <%= f.select :difficulty_level,
                       Project.difficulty_levels.keys.map { |level| [level.titleize, level] }, {}, {:class => "form-control custom"} %>
        </div>
        <div class="form-group">
          <h1>
            Research Fields
            <%= link_to raw('<i class="fa fa-plus-circle"></i> &nbsp;&nbsp;Add'), project_research_fields_index_path(@project), :method => :get, class: 'btn btn-success btn-sm' %>
          </h1>
          <% @project.project_research_fields.each_with_index do |project_research_field, index| %>
              <%= project_research_field.research_field.category %><% if index != @project.project_research_fields.length-1%>, <% end %>
          <% end %>
        </div>

        <% if (@project.name != nil) %>
            <h1>Team Members
              <%= link_to raw('<i class="fa fa-plus-circle"></i> &nbsp;&nbsp;Add'), add_user_to_project_path(@project), :method => :get, class: 'btn btn-success btn-sm' %>
            </h1>

            <table class="table table-striped col-lg-6">
              <tbody>
              <% @project.teams.each do |team_member| %>
                  <tr>
                    <% if team_member.user.profile.first_name %>
                        <td><%= team_member.user.profile.first_name + ' ' + team_member.user.profile.last_name %>
                        <td>
                          <%= link_to raw('<i class="fa fa-trash"></i> &nbsp;&nbsp;Remove'), remove_user_team_path(@project, :user_id => team_member.user.id), data: {confirm: 'Are you sure?'}, :method => :delete, class: 'btn btn-danger btn-sm' %>
                        </td>
                    <% end %>
                  </tr>
              <% end %>
        <% end %>

        </tbody>
        </table>

        <%= f.submit 'Submit', :class => 'btn btn-lg btn-primary' %>
      </fieldset>

  <% end %>
</div>

<nav>
  <ul class="pager">
    <li><%= link_to 'Back', projects_path %></li>
  </ul>
</nav>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Projects</h1>


<div class="m-t-25">
  <div class="pull-right">
    <%= link_to 'Create New Project', new_project_path, class: 'btn btn-success btn-lg' %>
  </div>

  <ul class="nav nav-pills">
    <li role="presentation" class="<%= (params[:status] == nil) ? '' : 'active' %>active"><a href="?">All</a></li>
    <% Project.statuses.keys.map do |status| %>
        <li role="presentation" class="<%= (params[:status] == status) ? 'active' : '' %>">
          <a href="?status=<%= status %>"><%= status.titleize %></a></li>
    <% end %>
  </ul>
</div>


<h3><%= @total_projects_count != 0 ? ('Showing ' + pluralize(@total_projects_count, 'project') + ' found:') : 'No Projects found!' %> </h3>

<% @projects.each do |project| %>
    <div class="jumbotron box m-t-15">
      <div class="row">
        <div class="col-lg-3">
          <strong>Project Name:</strong>
        </div>
        <div class="col-lg-6">
          <%= project.name %>
        </div>
        <div class="col-lg-3 text-right">
          <div class="label label-<%= get_css_class_by_status(Project.statuses[project.status]) %>"><%= project.status.titleize %></div>
        </div>
      </div>

      <% if project.department %>
          <div class="row">
            <div class="col-lg-3">
              <strong>Research Category:</strong>
            </div>
            <div class="col-lg-6">
              <%= project.department.name %>
            </div>
            <div class="col-lg-3">
            </div>
          </div>
      <% else %>
          <div class="row">
            <div class="col-lg-3">
              &nbsp;
            </div>
            <div class="col-lg-6">
              &nbsp;
            </div>
            <div class="col-lg-3">
              &nbsp;
            </div>
          </div>
      <% end %>

      <div class="row">

        <% if project.user.profile %>
            <div class="col-lg-3">
              <strong>Founding Member:</strong>
            </div>
            <div class="col-lg-6">
              <%= project.user.profile.first_name + ' ' + project.user.profile.last_name %>
            </div>
        <% end %>

        <div class="col-lg-3 text-right">
          <% if project.user.id == current_user.id %>
              <%= link_to 'View', project, class: 'btn btn-default btn-xs' %>
              <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-default btn-xs' %>
              <%= link_to 'Delete', project, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-default btn-xs' %>
          <% else %>
              <%= link_to 'View', project, class: 'btn btn-default btn-xs' %>
          <% end %>
        </div>
      </div>

    </div>
<% end %>
<%= will_paginate @projects, renderer: BootstrapPagination::Rails %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<div class="authform">
  <%= form_for(@project) do |f| %>
      <%= display_error_messages(@project) %>
      <fieldset>
        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :department %><br>
          <% departments = options_from_collection_for_select(@departments, 'id', 'name') %>
          <%= f.select :department_id, departments, {:prompt => true}, {:class => 'form-control custom'} %>
        </div>

        <div class="form-group">
          <%= f.label :status %><br>
          <%= f.select :status, Project.statuses.keys.map { |status| [status.titleize, status] }, {}, class: 'form-control custom' %>
        </div>
        <div class="form-group">
          <%= f.label :description %><br>
          <%= f.text_field :description, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :start_date %><br>
          <%= f.date_select :start_date, {}, {:class => "form-control custom"} %>
        </div>
        <div class="form-group">
          <%= f.label :end_date %><br>
          <%= f.date_select :end_date, {}, {:class => "form-control custom"} %>
        </div>
        <div class="form-group">
          <%= f.label :funding %><br>
          <div class="input-group col-lg-5">
            <span class="input-group-addon">$</span>
            <%= f.number_field :funding, class: 'form-control' %>
            <span class="input-group-addon">.00</span>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :difficulty_level %><br>
          <%= f.select :difficulty_level,
                       Project.difficulty_levels.keys.map { |level| [level.titleize, level] }, {}, {:class => "form-control custom"} %>
        </div>

        </tbody>
        </table>

        <%= f.submit 'Submit', :class => 'btn btn-lg btn-primary' %>
      </fieldset>

  <% end %>
</div>

<nav>
  <ul class="pager">
    <li><%= link_to 'Back', projects_path %></li>
  </ul>
</nav>

app/views/projects/show.html.erb
<h1 class="col-lg-12">View Project
  <% if @project.user.id == current_user.id && @project.status != 'complete' %>
      <%= link_to 'Mark Project as Complete', project_contributions_path(@project), class: 'btn btn-primary btn-sm pull-right' %>
  <% end %>
  <% if @project.user.id != current_user.id && @project.status != 'complete' # If is only not a founding member and not a completed project of course         %>
      <% @approved_join_requests = Request.where('user_id = ? and project_id = ? and type = ? and status = ?', current_user.id, @project.id, Request.request_types[:join], Request.request_statuses[:approved]) %>
      <% @unapproved_join_requests = Request.where('user_id = ? and project_id = ? and type = ? and status = ?', current_user.id, @project.id, Request.request_types[:join], Request.request_statuses[:unapproved]) %>
      <% @unapproved_leave_request = Request.where('user_id = ? and project_id = ? and type = ? and status = ?', current_user.id, @project.id, Request.request_types[:leave], Request.request_statuses[:unapproved]) %>
      <% @approved_leave_request = Request.where('user_id = ? and project_id = ? and type = ? and status = ?', current_user.id, @project.id, Request.request_types[:leave], Request.request_statuses[:approved]) %>

      <% if @approved_leave_request.length > 0 # Did user already make a request to join?          %>
          <%= link_to 'Left permanently about ' + time_ago_in_words(@approved_leave_request.first.updated_at).humanize + ' ago', '#', class: 'btn btn-primary btn-sm pull-right', :disabled => true %>
      <% elsif @unapproved_join_requests.length > 0 # Did user already make a request to join?          %>
          <%= link_to 'Join Request Sent', '#', class: 'btn btn-primary btn-sm pull-right', :disabled => true %>
      <% elsif @unapproved_leave_request.length > 0 %>
          <%= link_to 'Leave Request Sent', '#', class: 'btn btn-primary btn-sm pull-right', :disabled => true %>
      <% elsif @approved_join_requests.length > 0 # Did user already joined?          %>
          <%= link_to 'Leave Project', make_request_path(@project, Request.request_types[:leave]), :method => :post, class: 'btn btn-primary btn-sm pull-right' %>
      <% else %>
          <%= link_to 'Join Project', make_request_path(@project, Request.request_types[:join]), :method => :post, class: 'btn btn-primary btn-sm pull-right' %>
      <% end %>

  <% end %>
</h1>
<div class="jumbotron box m-t-10 col-lg-12">

  <div class="row m-t-10">
    <div class="col-lg-4 col-sm-12 col-xs-12">
      <strong>Name</strong>
    </div>
    <div class="col-lg-1 hidden-xs">
      :
    </div>
    <div class="col-lg-7 col-sm-12 col-xs-12">
      <%= @project.name %>
    </div>
  </div>
  <% if @project.department %>
      <div class="row m-t-10">
        <div class="col-lg-4 col-sm-12 col-xs-12">
          <strong>Department</strong>
        </div>
        <div class="col-lg-1 hidden-xs">
          :
        </div>
        <div class="col-lg-7 col-sm-12 col-xs-12">
          <%= @project.department.name %>
        </div>
      </div>
  <% end %>
  <div class="row m-t-10">
    <div class="col-lg-4 col-sm-12 col-xs-12">
      <strong>Status</strong>
    </div>
    <div class="col-lg-1 hidden-xs">
      :
    </div>
    <div class="col-lg-7 col-sm-12 col-xs-12">
      <div class="label label-<%= get_css_class_by_status(Project.statuses[@project.status]) %>"><%= @project.status.titleize %></div>
    </div>
  </div>
  <div class="row m-t-10">
    <div class="col-lg-4 col-sm-12 col-xs-12">
      <strong>Description</strong>
    </div>
    <div class="col-lg-1 hidden-xs">
      :
    </div>
    <div class="col-lg-7 col-sm-12 col-xs-12">
      <%= @project.description %>
    </div>
  </div>
  <div class="row m-t-10">
    <div class="col-lg-4 col-sm-12 col-xs-12">
      <strong>Founding Member</strong>
    </div>
    <div class="col-lg-1 hidden-xs">
      :
    </div>
    <div class="col-lg-7 col-sm-12 col-xs-12">
      <%= @project.user.profile.first_name + ' ' + @project.user.profile.last_name %>
    </div>
  </div>
  <div class="row m-t-10">
    <div class="col-lg-4 col-sm-12 col-xs-12">
      <strong>Start Date</strong>
    </div>
    <div class="col-lg-1 hidden-xs">
      :
    </div>
    <div class="col-lg-7 col-sm-12 col-xs-12">
      <%= @project.start_date.to_formatted_s(:long_ordinal) %>
    </div>
  </div>
  <div class="row m-t-10">
    <div class="col-lg-4 col-sm-12 col-xs-12">
      <strong>End Date</strong>
    </div>
    <div class="col-lg-1 hidden-xs">
      :
    </div>
    <div class="col-lg-7 col-sm-12 col-xs-12">
      <%= @project.end_date.to_formatted_s(:long_ordinal) %>
    </div>
  </div>
  <div class="row m-t-10">
    <div class="col-lg-4 col-sm-12 col-xs-12">
      <strong>Funding</strong>
    </div>
    <div class="col-lg-1 hidden-xs">
      :
    </div>
    <div class="col-lg-7 col-sm-12 col-xs-12">
      <%= number_to_currency(@project.funding, precision: 0) %>
    </div>
  </div>
  <div class="row m-t-10">
    <div class="col-lg-4 col-sm-12 col-xs-12">
      <strong>Difficulty level:</strong>
    </div>
    <div class="col-lg-1 hidden-xs">
      :
    </div>
    <div class="col-lg-7 col-sm-12 col-xs-12">
      <%= @project.difficulty_level.titleize %>
    </div>
  </div>
  <% if @project.project_research_fields.length != 0 %>
      <div class="row m-t-10">
        <div class="col-lg-4 col-sm-12 col-xs-12">
          <strong>Research field:</strong>
        </div>
        <div class="col-lg-1 hidden-xs">
          :
        </div>
        <div class="col-lg-7 col-sm-12 col-xs-12">
          <% @project.project_research_fields.each_with_index do |project_research_field, index| %>
              <%= project_research_field.research_field.category %>
              <% if index != @project.project_research_fields.length - 1 %>,
              <% end %>
          <% end %>
        </div>
      </div>
  <% end %>
  <% if @team_members_ids.length > 0 %>
      <div class="row m-t-10">
        <div class="col-lg-4 col-sm-12 col-xs-12">
          <strong>Current Team:</strong>
        </div>
        <div class="col-lg-1 hidden-xs">
          :
        </div>
        <div class="col-lg-7 col-sm-12 col-xs-12">
          <% @project.teams.each_with_index do |team_member, index| %>
              <% if team_member.user.profile || @project.user_id != current_user.id %>
                  <%= link_to team_member.user.profile.first_name + ' ' + team_member.user.profile.last_name, profile_path(team_member.user.profile) %>
                  <% if index != @project.teams.length - 1 %>,
                  <% end %>
              <% end %>
          <% end %>
        </div>
      </div>
  <% end %>
</div>
<br>

<div class="clearfix"></div>

<% if @project.user.id == current_user.id || @approved_join_requests.length > 0 && @approved_leave_request.length == 0 %>
<% if @project.user == current_user && @project.status != "complete" %>
    <div class="m-t-25">
      <h2 class="text-inline">Project Iterations</h2>
      <div class="text-inline pull-right">
        <%= link_to 'Create New Iteration', new_project_iteration_path(@project, @iteration), class: 'btn btn-success btn-lg' %>
      </div>
    </div>
<% else %>
    <div class="m-t-25">
      <h2 class="text-inline">Project Iterations</h2>
    </div>
<% end %>

<table class="table table-striped col-lg-9">
  <thead>
  <tr>
    <th>ID</th>
    <th>Iteration Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @counter = 1 %>
  <% @iterations.each do |iteration| %>
      <tr>
        <td><%= @counter %></td>
        <td><%= iteration.name %></td>
        <td>
          <% if @project.user_id == current_user.id && @project.status != "complete" %>
              <%= link_to 'View', project_iteration_path(@project, iteration), class: 'btn btn-default btn-xs' %>
              <%= link_to 'Edit', edit_project_iteration_path(@project, iteration), class: 'btn btn-default btn-xs' %>
              <%= link_to 'Delete', project_iteration_path(@project, iteration), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-default btn-xs' %>
          <% else %>
              <%= link_to 'View', project_iteration_path(@project, iteration), class: 'btn btn-default btn-xs' %>
          <% end %>
        </td>
      </tr>
      <% @counter = @counter + 1 %>
  <% end %>
  </tbody>
</table>
<% end %>

<div class="clearfix"></div>
<nav class="col-lg-9">
  <ul class="pager">
    <li><%= link_to 'Back', projects_path %></li>
  </ul>
</nav>
</div>