config/routes.rb
Rails.application.routes.draw do

  authenticate :user do
    get '/project_research_fields/project/:project_id', to: 'project_research_fields#index', as: 'project_research_fields_index'
    post '/project_research_fields/add/:research_field/project/:project_id', to: 'project_research_fields#add', as: 'project_research_fields_add'
    get 'contributions/project/:project_id' => 'contributions#contribute', as: 'submit_completion'
    get 'dashboard' => 'dashboard#index'
    get 'contributions/:project_id' => 'contributions#complete', as: 'project_contributions'
    get 'contributions/add/project/:project_id/user/:user_id' => 'contributions#add', as: 'add_contribution_to_project'
    post 'contributions/add/project/:project_id/user/:user_id' => 'contributions#save', as: 'save_contribution_to_project'
    post '/profile_research_fields/add/:research_field', to: 'profile_research_fields#add', as: 'profile_research_fields_add'
    get 'project/team/:project_id' => 'teams#new', as: 'add_user_to_project'
    post 'team/project/:project_id/user/:user_id' => 'teams#create', as: 'add_user_team'
    delete 'team/project/remove/:project_id/user/:user_id' => 'teams#destroy', as: 'remove_user_team'

    get 'search/projects/' => 'projects#search'
    post 'search/projects/' => 'projects#search', as: 'search_interesting_projects'
    resources :teams
    resources :contributions
    resources :projects do
      resources :iterations
    end
    resources :profile_research_fields
    resources :profiles
    resources :project_research_fields
    resources :tasks
    get 'iteration/:iteration_id/tasks/new' => 'tasks#new', as: 'new_iteration_tasks'
    post 'iteration/:iteration_id/tasks/new' => 'tasks#create'
    get 'iteration/:iteration_id/task/:id/edit' => 'tasks#edit', as: 'edit_iteration_task'
    post 'iteration/:iteration_id/task/:id/edit' => 'tasks#edit'

    resources :requests
    post 'requests/project/:project_id/:request_type' => 'requests#make', as: 'make_request'
    post 'requests/:id/:type' => 'requests#action', as: 'take_request_action'
    get 'requests/:id/remove/points' => 'requests#leave', as: 'leave_request_remove_points'
    patch 'requests/:id/remove/points' => 'requests#approve_leave'

  end

  devise_for :users, controllers: { registrations: "registrations" }

  root 'static_pages#home'










end

app/models/contribution.rb
# == Schema Information
#
# Table name: contributions
#
#  id             :integer          not null, primary key
#  score          :integer
#  money_received :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :integer
#  project_id     :integer
#



class Contribution < ActiveRecord::Base
  validates :score,
            presence: true,
            numericality: {
                only_integer: true,
                greater_than_or_equal_to: -100,
                less_than_or_equal_to: 10000
            }

  validates :money_received,
            presence: true,
            numericality: {
                only_integer: true,
                greater_than_or_equal_to: 0,
                less_than_or_equal_to: 100000000
            }

  belongs_to :user
  belongs_to :project
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]

  # GET /contributions
  # GET /contributions.json
  def index
    @contributions = Contribution.all
    @contributions = Contribution.where("user_id == ?", current_user.id)

    if params[:show]
      if params[:show] == 'earned'
        @contributions = Contribution.where("score > ? AND money_received > ? AND user_id == ?", 0, 0, current_user.id)
      end
      if params[:show] == 'lost'
        @contributions = Contribution.where("score < ? AND user_id == ?", 0, current_user.id)
      end
    end
  end

  def complete
    @contributions = Contribution.where('project_id == ?', params[:project_id])
    @project = Project.find(params[:project_id])
    @teams = Team.where('project_id == ?', params[:project_id])
  end

  def add
    @contribution = Contribution.new
    @project = Project.find(params[:project_id])
    @team_member = User.find(params[:user_id])
  end

  def save
    @contribution = Contribution.new(contribution_params)
    @contribution.user_id = params[:user_id]
    @contribution.project_id = params[:project_id]
    @project = Project.find(params[:project_id])

    respond_to do |format|
      if @contribution.save
        format.html { redirect_to project_contributions_path(@project), notice: 'Contribution was successfully created.' }
        format.json { render :show, status: :created, location: @contribution }
      else
        format.html { render :new }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /contributions/1x`1`
  # GET /contributions/1.json
  def show
  end

  # GET /contributions/new
  def new
    @contribution = Contribution.new
  end

  # GET /contributions/1/edit
  def edit
  end

  # POST /contributions
  # POST /contributions.json
  def create
    @contribution = Contribution.new(contribution_params)

    respond_to do |format|
      if @contribution.save
        format.html { redirect_to @contribution, notice: 'Contribution was successfully created.' }
        format.json { render :show, status: :created, location: @contribution }
      else
        format.html { render :new }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contributions/1
  # PATCH/PUT /contributions/1.json
  def update
    respond_to do |format|
      if @contribution.update(contribution_params)
        format.html { redirect_to @contribution, notice: 'Contribution was successfully updated.' }
        format.json { render :show, status: :ok, location: @contribution }
      else
        format.html { render :edit }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributions/1
  # DELETE /contributions/1.json
  def destroy
    @contribution.destroy
    respond_to do |format|
      format.html { redirect_to contributions_url, notice: 'Contribution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def contribute
    @project = Project.find(params[:project_id])
    @project.status = :complete
    @project.save!
    redirect_to @project, notice: 'Project was successfully completed.'
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_contribution
    @contribution = Contribution.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contribution_params
    params.require(:contribution).permit(:score, :money_received )
  end
end

app/helpers/contributions_helper.rb
module ContributionsHelper

  def get_positive_contribution(project_id, user_id)
    return Contribution.where('project_id == ? AND user_id == ? AND score > ? AND money_received > ?', project_id, user_id, 0, 0).first
  end

end

app/views/contributions/_form.html.erb
<%= form_for(@contribution) do |f| %>
    <%= display_error_messages(@project) %>

    <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :money_received %><br>
    <%= f.number_field :money_received %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contributions/add.html.erb
<div class="row">
<div class="col-lg-8">

  <h1>New Contribution</h1>

  <h5>Project Name: <%= @project.name %></h5>
  <h5>Team Member: <%= @team_member.profile.first_name + ' ' + @team_member.profile.last_name %></h5>

  <%= form_for(@contribution, url: add_contribution_to_project_path) do |f| %>
      <% if @contribution.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

            <ul>
              <% @contribution.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :score %><br>
        <%= f.number_field :score, class: "form-control" %>
      </div>
      <div class="field">
        <div class="form-group">
          <%= f.label 'Amount (in dollars)', class: "sr-only" %><br>
          <div class="input-group">
            <div class="input-group-addon">$</div>
            <%= f.number_field :money_received, class: "form-control"  %>
            <div class="input-group-addon">.00</div>
          </div>
        </div>
      </div>
      <div class="actions">
        <%= f.submit 'Add Contribution', :class => 'btn btn-lg btn-primary' %>
      </div>
  <% end %>


  <%= link_to 'Back', contributions_path %>
</div>

</div>

app/views/contributions/complete.html.erb

<div class="row">
  <h1>Mark Project As Complete</h1>
  <div class="jumbotron box m-t-15">
    <div class="row">
      <div class="col-lg-3">
        <strong>Project Name:</strong>
      </div>
      <div class="col-lg-6">
        <%= @project.name %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3">
        <strong>Department:</strong>
      </div>
      <div class="col-lg-6">
        <%= @project.department.name %>
      </div>
    </div>
  </div>

  <h2>Award Points and Money</h2>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Points</th>
      <th>Money</th>
    </tr>
    </thead>
    <tbody>
    <% @teams.each_with_index do |team, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= team.user.profile.first_name %></td>
          <td><%= team.user.profile.last_name %></td>
          <% if contribution = get_positive_contribution(params[:project_id], team.user_id) %>
              <td><%= contribution.score %></td>
              <td><%= number_to_currency(contribution.money_received, precision: 0) %></td>
          <% else %>
              <td colspan="2" class="text-center"><%= link_to 'Award points and Contribution', add_contribution_to_project_path(@project, :user_id => team.user.id), class: 'btn btn-default btn-xs' %></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
    <%= link_to 'Submit', submit_completion_path(@project), :class => 'btn btn-lg btn-primary' %>
</div>

app/views/contributions/edit.html.erb
<h1>Editing Contribution</h1>

<%= render 'form' %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Contributions</h1>
<ul class="nav nav-pills">
  <li role="presentation" class="<%= 'active' if !params[:show] || params[:show] == 'all' %>"><a href="?show=all">All</a></li>
  <li role="presentation" class="<%= 'active' if params[:show] == 'earned' %>"><a href="?show=earned">Points earned and Money received</a></li>
  <li role="presentation" class="<%= 'active' if params[:show] == 'lost' %>"><a href="?show=lost">Points Lost</a></li>
</ul>


<% @contributions.each do |contribution| %>
    <div class="jumbotron box m-t-15">
      <div class="row">
        <div class="col-lg-3">
          Project Name
        </div>
        <div class="col-lg-6">
          :
        </div>
        <div class="col-lg-3">
          <%= contribution.project ? contribution.project.name : '' %>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-3">
          Points <%= contribution.score < 0 ? 'Lost': 'Earned' %>
        </div>
        <div class="col-lg-6">
          :
        </div>
        <div class="col-lg-3">
          <%= contribution.score %>
        </div>
      </div>

      <% if contribution.money_received != 0 %>
      <div class="row">
        <div class="col-lg-3">
          Money received
        </div>
        <div class="col-lg-6">
          :
        </div>
        <div class="col-lg-3">
          $ <%= contribution.money_received %>
        </div>
      </div>
      <% end %>

    </div>
<% end %>
<% if @contributions.length == 0 %>
<h3>No such contributions found!</h3>
<% end %>

app/views/contributions/new.html.erb
<h1>New Contribution</h1>

<%= render 'form' %>

<%= link_to 'Back', contributions_path %>

app/views/contributions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @contribution.score %>
</p>

<p>
  <strong>Money received:</strong>
  <%= @contribution.money_received %>
</p>

<%= link_to 'Edit', edit_contribution_path(@contribution) %> |
<%= link_to 'Back', contributions_path %>