config/routes.rb
Rails.application.routes.draw do

  authenticate :user do
    get '/project_research_fields/project/:project_id', to: 'project_research_fields#index', as: 'project_research_fields_index'
    post '/project_research_fields/add/:research_field/project/:project_id', to: 'project_research_fields#add', as: 'project_research_fields_add'
    get 'contributions/project/:project_id' => 'contributions#contribute', as: 'submit_completion'
    get 'dashboard' => 'dashboard#index'
    get 'contributions/:project_id' => 'contributions#complete', as: 'project_contributions'
    get 'contributions/add/project/:project_id/user/:user_id' => 'contributions#add', as: 'add_contribution_to_project'
    post 'contributions/add/project/:project_id/user/:user_id' => 'contributions#save', as: 'save_contribution_to_project'
    post '/profile_research_fields/add/:research_field', to: 'profile_research_fields#add', as: 'profile_research_fields_add'
    get 'project/team/:project_id' => 'teams#new', as: 'add_user_to_project'
    post 'team/project/:project_id/user/:user_id' => 'teams#create', as: 'add_user_team'
    delete 'team/project/remove/:project_id/user/:user_id' => 'teams#destroy', as: 'remove_user_team'

    get 'search/projects/' => 'projects#search'
    post 'search/projects/' => 'projects#search', as: 'search_interesting_projects'
    resources :teams
    resources :contributions
    resources :projects do
      resources :iterations
    end
    resources :profile_research_fields
    resources :profiles
    resources :project_research_fields
    resources :tasks
    get 'iteration/:iteration_id/tasks/new' => 'tasks#new', as: 'new_iteration_tasks'
    post 'iteration/:iteration_id/tasks/new' => 'tasks#create'
    get 'iteration/:iteration_id/task/:id/edit' => 'tasks#edit', as: 'edit_iteration_task'
    post 'iteration/:iteration_id/task/:id/edit' => 'tasks#edit'

    resources :requests
    post 'requests/project/:project_id/:request_type' => 'requests#make', as: 'make_request'
    post 'requests/:id/:type' => 'requests#action', as: 'take_request_action'
    get 'requests/:id/remove/points' => 'requests#leave', as: 'leave_request_remove_points'
    patch 'requests/:id/remove/points' => 'requests#approve_leave'

  end

  devise_for :users, controllers: { registrations: "registrations" }

  root 'static_pages#home'










end

app/models/iteration.rb
# == Schema Information
#
# Table name: iterations
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  project_id :integer
#

class Iteration < ActiveRecord::Base
  
  validates :name, 
  			presence: true,
  			length: { minimum: 2, maximum: 50 }
  			
  has_many :tasks
  belongs_to :project
end

app/controllers/iterations_controller.rb
class IterationsController < ApplicationController
  before_action :set_iteration, only: [:show, :edit, :update, :destroy]

  # GET /iterations
  # GET /iterations.json
  def index
    @iterations = Iteration.all
  end

  # GET /iterations/1
  # GET /iterations/1.json
  def show
    @project = Project.find_by_id(params[:project_id])
    @tasks = Task.where('iteration_id = ?', @iteration.id)
  end

  # GET /iterations/new
  def new
    @iteration = Iteration.new
    @project = Project.find_by_id(params[:project_id])
  end

  # GET /iterations/1/edit
  def edit 
    @project = Project.find_by_id(params[:project_id])
  end

  # POST /iterations
  # POST /iterations.json
  def create
    @iteration = Iteration.new(iteration_params)

    @project = Project.find_by_id(params[:project_id])

    respond_to do |format|
      if @iteration.save
        format.html { redirect_to project_path(@project), notice: 'Iteration was successfully created.' }
        format.json { render :show, status: :created, location: @iteration }
      else
        format.html { render :new }
        format.json { render json: @iteration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /iterations/1
  # PATCH/PUT /iterations/1.json
  def update
    @project = Project.find_by_id(params[:project_id])
    respond_to do |format|
      if @iteration.update(iteration_params)
        format.html { redirect_to project_path(@iteration.project.id), notice: 'Iteration was successfully updated.' }
        format.json { render :show, status: :ok, location: @iteration }
      else
        format.html { render :edit }
        format.json { render json: @iteration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iterations/1
  # DELETE /iterations/1.json
  def destroy
    
    @project = Project.find_by_id(params[:project_id])

    @iteration.destroy
    respond_to do |format|
      format.html { redirect_to project_path(@project), notice: 'Iteration was successfully destroyed.' }
      # format.html { redirect_to project_path(params[:project_id]), notice: 'Iteration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_iteration
      @iteration = Iteration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def iteration_params
      params.require(:iteration).permit(:name, :project_id)
    end
end

app/helpers/iterations_helper.rb
module IterationsHelper
end

app/views/iterations/_form.html.erb
<%= form_for(@iteration, url: project_iteration_path(@project, @iteration)) do |f| %>
    <% if @iteration.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@iteration.errors.count, "error") %> prohibited this iteration from being saved:</h2>

          <ul>
            <% @iteration.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <%= f.hidden_field :project_id, :value => @project.id %>

    <div class="actions">
      <%= f.submit 'Submit', class: 'btn btn-primary'%>
    </div>
<% end %>

app/views/iterations/edit.html.erb
<h1>Editing Iteration</h1>

<%= form_for(@iteration, url: project_iteration_path(@project, @iteration)) do |f| %>
    <% if @iteration.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@iteration.errors.count, "error") %> prohibited this iteration from being saved:</h2>

          <ul>
            <% @iteration.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <%= f.hidden_field :project_id, :value => @project.id %>

    <div class="actions">
      <%= f.submit 'Submit', class: 'btn btn-primary'%>
    </div>
<% end %>


<%= link_to 'Show', project_iteration_path(@project, @iteration) %> |
<%= link_to 'Back', project_path(@project) %>

app/views/iterations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Iterations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @iterations.each do |iteration| %>
      <tr>
        <td><%= iteration.name %></td>
        <td><%= link_to 'Show', iteration %></td>
        <td><%= link_to 'Edit', edit_iteration_path(iteration) %></td>
        <td><%= link_to 'Destroy', iteration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Iteration', new_iteration_path %>

app/views/iterations/new.html.erb
<h1>Create Iteration</h1>

<%= form_for(@iteration, url: project_iterations_path(@project)) do |f| %>
    <% if @iteration.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@iteration.errors.count, "error") %> prohibited this iteration from being saved:</h2>

          <ul>
            <% @iteration.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <%= f.hidden_field :project_id, :value => @project.id %>

    <div class="actions">
      <%= f.submit 'Submit', class: 'btn btn-primary'%>
    </div>
<% end %>

<%= link_to 'Back', project_path(@project) %>

app/views/iterations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Iteration Name:</strong>
  <%= @iteration.name %>
</p>


<div class="m-t-25">
  <h2 class="text-inline">Iteration Tasks</h2>
  <% if @iteration.project.status != "complete" %>
      <div class="pull-right text-inline">
        <%= link_to 'Create New Task', new_iteration_tasks_path(@iteration), class: 'btn btn-success btn-lg' %>
      </div>
  <% end %>
</div>

<table class="table table-striped col-lg-9">
  <thead>
  <tr>
    <th>ID</th>
    <th>Task Name</th>
    <th>Status</th>
    <th>Due Date</th>
    <th>Assigned To</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @counter = 1 %>
  <% @tasks.each do |task| %>
      <tr>
        <td><%= @counter %></td>
        <td><%= task.name %></td>
        <td><%= task.status.titleize %></td>
        <td><%= task.due_date.to_formatted_s(:long_ordinal) %></td>
        <% @assigned_user_profile = User.find(task.assigned_user) %>
        <td><%= @assigned_user_profile.profile.first_name %></td>
        <td>
          <% if task.user_id == current_user.id || task.assigned_user == current_user %>
              <% if @iteration.project.status != "complete" %>
                  <%= link_to 'View', task_path(task), class: 'btn btn-default btn-xs' %>

                  <%= link_to 'Edit', edit_iteration_task_path(task.iteration_id, task), class: 'btn btn-default btn-xs' %>
                  <%= link_to 'Delete', task_path(task, :iteration_id => task.iteration_id), method: :delete, data: {confirm: 'Are you sure?'}, :iteration_id => task.iteration_id, class: 'btn btn-default btn-xs' %>
              <% end %>
          <% else %>
              <%= link_to 'View', task_path(task), class: 'btn btn-default btn-xs' %>
          <% end %>
        </td>
      </tr>
      <% @counter = @counter + 1 %>
  <% end %>
  </tbody>
</table>


<div class="clearfix"></div>
<nav class="col-lg-9">
  <ul class="pager">
    <li><%= link_to 'Edit', edit_project_iteration_path(@project, @iteration) %></li>
    <li><%= link_to 'Back', project_path(@project) %></li>
  </ul>
</nav>