config/routes.rb
Rails.application.routes.draw do

  authenticate :user do
    get '/project_research_fields/project/:project_id', to: 'project_research_fields#index', as: 'project_research_fields_index'
    post '/project_research_fields/add/:research_field/project/:project_id', to: 'project_research_fields#add', as: 'project_research_fields_add'
    get 'contributions/project/:project_id' => 'contributions#contribute', as: 'submit_completion'
    get 'dashboard' => 'dashboard#index'
    get 'contributions/:project_id' => 'contributions#complete', as: 'project_contributions'
    get 'contributions/add/project/:project_id/user/:user_id' => 'contributions#add', as: 'add_contribution_to_project'
    post 'contributions/add/project/:project_id/user/:user_id' => 'contributions#save', as: 'save_contribution_to_project'
    post '/profile_research_fields/add/:research_field', to: 'profile_research_fields#add', as: 'profile_research_fields_add'
    get 'project/team/:project_id' => 'teams#new', as: 'add_user_to_project'
    post 'team/project/:project_id/user/:user_id' => 'teams#create', as: 'add_user_team'
    delete 'team/project/remove/:project_id/user/:user_id' => 'teams#destroy', as: 'remove_user_team'

    get 'search/projects/' => 'projects#search'
    post 'search/projects/' => 'projects#search', as: 'search_interesting_projects'
    resources :teams
    resources :contributions
    resources :projects do
      resources :iterations
    end
    resources :profile_research_fields
    resources :profiles
    resources :project_research_fields
    resources :tasks
    get 'iteration/:iteration_id/tasks/new' => 'tasks#new', as: 'new_iteration_tasks'
    post 'iteration/:iteration_id/tasks/new' => 'tasks#create'
    get 'iteration/:iteration_id/task/:id/edit' => 'tasks#edit', as: 'edit_iteration_task'
    post 'iteration/:iteration_id/task/:id/edit' => 'tasks#edit'

    resources :requests
    post 'requests/project/:project_id/:request_type' => 'requests#make', as: 'make_request'
    post 'requests/:id/:type' => 'requests#action', as: 'take_request_action'
    get 'requests/:id/remove/points' => 'requests#leave', as: 'leave_request_remove_points'
    patch 'requests/:id/remove/points' => 'requests#approve_leave'

  end

  devise_for :users, controllers: { registrations: "registrations" }

  root 'static_pages#home'










end

app/views/layouts/_container.html.erb
<div class="row">
  <% if user_signed_in? && controller.controller_name != 'static_pages' %>
      <div id="wrapper">
        <%= render 'layouts/sidebar' %>
        <!-- Page Content -->
        <div id="page-content-wrapper">
          <div class="container-fluid">
            <div class="row">
              <div class="col-lg-12">
                <%= render 'layouts/messages' %>
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
        <!-- /#page-content-wrapper -->
      </div>
      <!-- /#wrapper -->
<% else %>
      <div class="col-lg-12">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
<% end %>
</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="site-footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-lg-12">
        <section class="pull-left text-muted">
          &copy <%= Date.today.year %>, iHunt. All rights reserved.
        </section>
        <section class="pull-right">
          Made with <span class="glyphicon glyphicon-heart text-danger" aria-hidden="true"></span> by Team Bharat.
        </section>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> <%= user_signed_in? ? 'col-sm-8' : 'col-sm-offset-3 col-sm-6' %> m-t-15">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, raw('<span class="glyphicon glyphicon-exclamation-sign"></span> ' + msg), :id => "flash_#{name}" %>
        </div>
        <div class="clearfix"></div>

    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to raw('<i class="fa fa-lightbulb-o"></i> iHunt'), root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add top right navigation links to this file %>
<% if user_signed_in? %>
    <% if controller.controller_name != 'static_pages' %>
      <li><a href="#menu-toggle" id="menu-toggle"><i class="fa fa-angle-double-left"></i> Toggle Menu</a></li>
    <% end %>
    <li class="dropdown">
      <% if current_user.profile.blank? or current_user.profile.first_name.blank?%>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hi, User<span class="caret"></span></a>
      <% else %>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.profile.first_name %> <%= current_user.profile.last_name %><span class="caret"></span></a>
      <% end %>
      <ul class="dropdown-menu">
        <li class="<%= 'active' if current_page?(edit_user_registration_path) %>"><%= link_to 'Modify Account', edit_user_registration_path %></li>
        <% if current_user.profile.blank? %>
          <li><a href="<%= new_profile_path %>">Complete Profile</a></li>
        <% else %>
          <li><a href="<%= profile_path(current_user.profile) %>">My Profile</a></li>
        <% end %>
        <li role="separator" class="divider"></li>
        <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
      </ul>
    </li>
<% else %>
    <li><%= link_to 'Register', new_user_registration_path %></li>
    <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="active">
      <%= link_to raw('<span class="fa fa-tachometer"></span> Dashboard'), dashboard_path, :class => current_class?(dashboard_path) %>
    </li>
    <li>
      <%= link_to raw('<span class="fa fa-search"></span> Search Projects'), search_interesting_projects_path, :class => current_class?(search_interesting_projects_path) %>
    </li>
    <li>
      <%= link_to raw('<span class="fa fa-briefcase"></span> My Projects'), projects_path, :class => current_class?(projects_path)  %>
    </li>
    <li>
      <%= link_to raw('<span class="fa fa-tasks"></span> My Tasks'), tasks_path, :class => current_class?(tasks_path)  %>
    </li>
    <li>
      <%= link_to raw('<span class="fa fa-bell"></span> My Requests'), requests_path, :class => current_class?(requests_path)  %>
    </li>
    <li>
      <%= link_to raw('<span class="fa fa-money"></span> My Contributions'), contributions_path, :class => current_class?(contributions_path) %>
    </li>
  </ul>
</div>
<!-- /#sidebar-wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "iHunt" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "iHunt" %>">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <!--<%= javascript_include_tag 'maskedinput' %>-->
  <%= csrf_meta_tags %>
</head>
<body class="controller-<%= controller.controller_name %> action-<%= controller.action_name %> signedin-<%= user_signed_in? %>">
<header>
  <%= render 'layouts/navigation' %>
</header>
<main role="main" class="container page-wrap">
  <%= render 'layouts/container' %>
</main>
<%= render 'layouts/footer' %>
<%= javascript_include_tag 'application', 'data-turbolinks-eval' => false %>
</body>
</html>